apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"creationTimestamp":"2020-02-27T16:33:35Z","name":"update-scores","namespace":"kafka-saas","selfLink":"/apis/batch/v1beta1/namespaces/kafka-saas/cronjobs/update-scores","uid":"e64b3d0e-597e-11ea-bc71-0a9e36e5582e"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=8","utils","update-scores","--app.window=1h"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"es-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_CREDENTIALS","valueFrom":{"secretKeyRef":{"key":"creds","name":"elastic-user"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:26ea303","imagePullPolicy":"Always","name":"fixer","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"OnFailure","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}},"schedule":"0 * * * *","startingDeadlineSeconds":10000,"successfulJobsHistoryLimit":1,"suspend":true}}
  creationTimestamp: 2020-02-27T16:33:35Z
  name: update-scores
  namespace: kafka-saas
  resourceVersion: "177912737"
  selfLink: /apis/batch/v1beta1/namespaces/kafka-saas/cronjobs/update-scores
  uid: e64b3d0e-597e-11ea-bc71-0a9e36e5582e
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /hyperdark
            - --log.verbosity=8
            - utils
            - update-scores
            - --app.window=1h
            env:
            - name: HYPERDARK_KAFKA_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: kafka-cluster
                  name: endpoints
            - name: HYPERDARK_ES_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: es-cluster
                  name: endpoints
            - name: HYPERDARK_ES_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: creds
                  name: elastic-user
            image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:26ea303
            imagePullPolicy: Always
            name: fixer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  startingDeadlineSeconds: 10000
  successfulJobsHistoryLimit: 1
  suspend: true
status:
  lastScheduleTime: 2020-06-14T12:00:00Z
