apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"trainer-composite","namespace":"kafka-saas"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["/trainer","--log.verbosity=10","composite"],"env":[{"name":"TRAINER_COMPOSITE_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"TRAINER_COMPOSITE_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}},{"name":"TRAINER_COMPOSITE_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/trainer:test","imagePullPolicy":"Always","name":"trainer","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"restartPolicy":"Never"}}}},"schedule":"0/5 * * * *","successfulJobsHistoryLimit":1}}
  creationTimestamp: 2019-08-26T07:56:17Z
  name: trainer-composite
  namespace: kafka-saas
  resourceVersion: "225756559"
  selfLink: /apis/batch/v1beta1/namespaces/kafka-saas/cronjobs/trainer-composite
  uid: fc273d6b-c7d6-11e9-bc71-0a9e36e5582e
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /trainer
            - --log.verbosity=10
            - composite
            env:
            - name: TRAINER_COMPOSITE_CACHE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: redis-server
                  name: endpoints
            - name: TRAINER_COMPOSITE_CACHE_CLUSTER_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: redis-cluster
                  name: endpoints
            - name: TRAINER_COMPOSITE_DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: postgres-cluster
                  name: endpoints
            image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/trainer:test
            imagePullPolicy: Always
            name: trainer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: FallbackToLogsOnError
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/5 * * * *
  successfulJobsHistoryLimit: 1
  suspend: false
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: trainer-composite-1599234000
    namespace: kafka-saas
    resourceVersion: "225756555"
    uid: 3ec845e4-eec5-11ea-8d6d-0a9e36e5582e
  lastScheduleTime: 2020-09-04T15:40:00Z
