apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"bounce-leadoff-traffic-doc","namespace":"kafka-saas"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"metadata":{"creationTimestamp":null},"spec":{"template":{"metadata":{"creationTimestamp":null,"labels":{"run":"bounce-leadoff-traffic-doc"}},"spec":{"containers":[{"args":["/bin/bash","-c","/kubectl patch deployment leadoff-traffic-doc -p \"{\\\"spec\\\":{\\\"template\\\":{\\\"metadata\\\":{\\\"annotations\\\":{\\\"date\\\":\\\"$(date +%s)\\\"}}}}}\""],"image":"activeshadow/kubectl:v1.12.7","imagePullPolicy":"IfNotPresent","name":"kubectl","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"OnFailure","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"kubectl","serviceAccountName":"kubectl","terminationGracePeriodSeconds":30}}}},"schedule":"0 * * * *","successfulJobsHistoryLimit":1,"suspend":false}}
  creationTimestamp: 2020-05-15T02:41:43Z
  name: bounce-leadoff-traffic-doc
  namespace: kafka-saas
  resourceVersion: "160922578"
  selfLink: /apis/batch/v1beta1/namespaces/kafka-saas/cronjobs/bounce-leadoff-traffic-doc
  uid: 9c96b42b-9655-11ea-b7e4-02c6bb02f104
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: bounce-leadoff-traffic-doc
        spec:
          containers:
          - args:
            - /bin/bash
            - -c
            - /kubectl patch deployment leadoff-traffic-doc -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"$(date
              +%s)\"}}}}}"
            image: activeshadow/kubectl:v1.12.7
            imagePullPolicy: IfNotPresent
            name: kubectl
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: kubectl
          serviceAccountName: kubectl
          terminationGracePeriodSeconds: 30
  schedule: 0,20,40 * * * *
  successfulJobsHistoryLimit: 1
  suspend: true
status:
  lastScheduleTime: 2020-05-15T14:00:00Z
