apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    cert-manager.io/cluster-issuer: letsencrypt    
    ingress.kubernetes.io/auth-realm: 'Authentication Required - Kibana'
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: kibana
spec:
  rules:
  - host: jumbotron.dari.ae
    http:
      paths:
      - backend:
          serviceName: kibana-kibana
          servicePort: 5601
  tls:
  - hosts:
    - jumbotron.dari.ae
    secretName: kibana-ingress-tls
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
data:
  # vince / rei5iel7Xaiy
  auth: dmluY2U6JGFwcjEkMFhsVW9XbTgkdC4zSThNZUhBV2JPT2paSGppQVMyMAo=
type: Opaque
