apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/version: latest
  name: archive-traffic
  namespace: batch
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/version: latest
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/version: latest
        spec:
          containers:
          - args:
            - --retain_days=61
            command:
            - /scripts/archive-traffic.sh
            env:
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: reporting-db
                  name: endpoints
            - name: ES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: es-cluster
                  name: endpoints
            - name: ES_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: es-creds
                  name: endpoints
            image: justindarkcubed/batch:latest
            imagePullPolicy: IfNotPresent
            name: batch
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /scripts
              name: job-scripts
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 511
              name: job-scripts
            name: job-scripts
  schedule: 30 5 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
