apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openvas
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: openvas
    spec:
      containers:
      - args:
        - /start
        image: quay.io/darkcubed/openvas-full:1.0
        imagePullPolicy: IfNotPresent
        name: openvas
        ports:
        - containerPort: 9390
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /openvas/results
          name: results
        - mountPath: /var/lib/openvas/mgr
          name: mgr
      hostNetwork: true
      imagePullSecrets:
      - name: quay.io
      nodeSelector:
        appliance: squirrel
      volumes:
      - hostPath:
          path: /opt/darkcubed/openvas/results
          type: DirectoryOrCreate
        name: results
      - hostPath:
          path: /opt/darkcubed/openvas/mgr
          type: DirectoryOrCreate
        name: mgr
