---
apiVersion: v1
kind: Service
metadata:
  name: beanstalkd
  labels:
    run: beanstalkd
spec:
  ports:
    - port: 11300
  selector:
    run: beanstalkd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beanstalkd
  labels:
    run: beanstalkd
    version: "1.10"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: beanstalkd
        version: "1.10"
    spec:
      containers:
        - name: beanstalkd
          image: activeshadow/beanstalkd:latest
          ports:
            - name: beanstalk
              containerPort: 11300
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          livenessProbe:
            tcpSocket:
              port: 11300
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 11300
            initialDelaySeconds: 5
            timeoutSeconds: 1
