apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"agent-block-replay"},"name":"agent-block-replay","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"agent-block-replay"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"agent-block-replay"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","agent","block","manage","--kafka.input-topic=TempBlockDocStream_2","--kafka.group-name=TempBlockDoc"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:146327d","imagePullPolicy":"Always","name":"agent","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2020-05-01T14:31:58Z
  generation: 2
  labels:
    app: agent-block-replay
  name: agent-block-replay
  namespace: kafka-saas
  resourceVersion: "155474611"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/agent-block-replay
  uid: 8342c331-8bb8-11ea-a064-067d46b7253a
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agent-block-replay
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agent-block-replay
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - agent
        - block
        - manage
        - --kafka.input-topic=TempBlockDocStream_2
        - --kafka.group-name=TempBlockDoc
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: postgres-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:146327d
        imagePullPolicy: Always
        name: agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2020-05-01T14:31:58Z
    lastUpdateTime: 2020-05-01T14:31:59Z
    message: ReplicaSet "agent-block-replay-74f5989dc4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2020-05-01T20:30:34Z
    lastUpdateTime: 2020-05-01T20:30:34Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
