apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"agent-mute-replay"},"name":"agent-mute-replay","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"agent-mute-replay"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"agent-mute-replay"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","agent","mute","manage","--kafka.input-topic=TempMuteDocStream_2","--kafka.group-name=TempMuteDoc"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:146327d","imagePullPolicy":"Always","name":"agent","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2020-05-01T14:35:50Z
  generation: 2
  labels:
    app: agent-mute-replay
  name: agent-mute-replay
  namespace: kafka-saas
  resourceVersion: "154515369"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/agent-mute-replay
  uid: 0daba180-8bb9-11ea-bc71-0a9e36e5582e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agent-mute-replay
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: agent-mute-replay
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - agent
        - mute
        - manage
        - --kafka.input-topic=TempMuteDocStream_2
        - --kafka.group-name=TempMuteDoc
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:146327d
        imagePullPolicy: Always
        name: agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2020-05-01T14:35:50Z
    lastUpdateTime: 2020-05-01T14:35:50Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
