apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "74"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"72"},"creationTimestamp":"2019-08-26T03:41:20Z","generation":130,"labels":{"app":"catcher-processor"},"name":"catcher-processor","namespace":"kafka-saas","selfLink":"/apis/apps/v1/namespaces/kafka-saas/deployments/catcher-processor","uid":"5e630516-c7b3-11e9-b7e4-02c6bb02f104"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":10,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"catcher-processor"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1574791214"},"creationTimestamp":null,"labels":{"app":"catcher-processor","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","catcher","process","--app.event.ratelimit.enabled","--app.event.ratelimit.debug.no-limit"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:3b36075","imagePullPolicy":"Always","name":"catcher","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2019-08-26T03:41:20Z
  generation: 132
  labels:
    app: catcher-processor
  name: catcher-processor
  namespace: kafka-saas
  resourceVersion: "231062209"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/catcher-processor
  uid: 5e630516-c7b3-11e9-b7e4-02c6bb02f104
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catcher-processor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1574791214"
      creationTimestamp: null
      labels:
        app: catcher-processor
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - catcher
        - process
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: redis-server
              name: endpoints
        - name: HYPERDARK_CACHE_CLUSTER_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: redis-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: catcher
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: 2020-08-27T11:04:44Z
    lastUpdateTime: 2020-08-27T11:04:44Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 132
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
