apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"catcher-listener"},"name":"catcher-listener","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"catcher-listener"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"catcher-listener","prom":"monitor"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["catcher-listener"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["/hyperdark","--log.verbosity=9","catcher","listen"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:0d5a6c7","imagePullPolicy":"Always","name":"catcher","ports":[{"containerPort":9102,"hostPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError","volumeMounts":[{"mountPath":"/var/certs","name":"certs"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"nodeSelector":{"kops.k8s.io/instancegroup":"syslog"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"dedicated","value":"udp-syslog"}],"volumes":[{"name":"certs","secret":{"defaultMode":420,"secretName":"syslog-tls"}}]}}}}
  creationTimestamp: 2020-01-10T20:15:41Z
  generation: 24
  labels:
    app: catcher-listener
  name: catcher-listener
  namespace: kafka-saas
  resourceVersion: "221879813"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/catcher-listener
  uid: f9824d6a-33e5-11ea-a064-067d46b7253a
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catcher-listener
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1590950789"
      creationTimestamp: null
      labels:
        app: catcher-listener
        prom: monitor
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - catcher-listener
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=9
        - catcher
        - listen
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: catcher
        ports:
        - containerPort: 9102
          hostPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/certs
          name: certs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kops.k8s.io/instancegroup: syslog
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: udp-syslog
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: syslog-tls
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2020-08-29T01:02:24Z
    lastUpdateTime: 2020-08-29T01:03:06Z
    message: ReplicaSet "catcher-listener-8c47b6657" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2020-08-29T01:03:19Z
    lastUpdateTime: 2020-08-29T01:03:19Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 24
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
