apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "22"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cleanup-report-forced"},"name":"cleanup-report-forced","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"cleanup-report-forced"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1584048513"},"creationTimestamp":null,"labels":{"app":"cleanup-report-forced","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","cleanup","report","--blackbox.endpoint=scorecard.prod:8080","--kafka.group-name=ForcedReport","--kafka.input-topic=ForceStream","--app.min-loop-delay=1ms","--app.max-loop-delay=1ms"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}},{"name":"HYPERDARK_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}},{"name":"CLEANUP_REPORT_BLACKBOX_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"bearer-token","name":"scorecard-auth"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:125fbaf","imagePullPolicy":"Always","name":"cleanup","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2020-01-17T22:55:08Z
  generation: 84
  labels:
    app: cleanup-report-forced
  name: cleanup-report-forced
  namespace: kafka-saas
  resourceVersion: "231864373"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/cleanup-report-forced
  uid: 68b2d62a-397c-11ea-b7e4-02c6bb02f104
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cleanup-report-forced
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1584048513"
      creationTimestamp: null
      labels:
        app: cleanup-report-forced
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - cleanup
        - report
        - --blackbox.endpoint=scorecard.prod:8080
        - --kafka.group-name=ForcedReport
        - --kafka.input-topic=ForceStream
        - --app.min-loop-delay=1ms
        - --app.max-loop-delay=1ms
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: redis-server
              name: endpoints
        - name: HYPERDARK_CACHE_CLUSTER_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: redis-cluster
              name: endpoints
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: postgres-cluster
              name: endpoints
        - name: CLEANUP_REPORT_BLACKBOX_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: bearer-token
              name: scorecard-auth
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:125fbaf
        imagePullPolicy: Always
        name: cleanup
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-08-12T17:45:12Z
    lastUpdateTime: 2020-08-12T17:45:12Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 84
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
