apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"11"},"creationTimestamp":"2019-08-19T17:57:36Z","generation":13,"labels":{"app":"coach-enricher"},"name":"coach-enricher","namespace":"kafka-saas","selfLink":"/apis/apps/v1/namespaces/kafka-saas/deployments/coach-enricher","uid":"d3f86415-c2aa-11e9-984d-02b425e82e0e"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"coach-enricher"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1587159792"},"creationTimestamp":null,"labels":{"app":"coach-enricher","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","coach","enrich"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:615bafb","imagePullPolicy":"Always","name":"coach","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2019-08-19T17:57:36Z
  generation: 14
  labels:
    app: coach-enricher
  name: coach-enricher
  namespace: kafka-saas
  resourceVersion: "219763855"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/coach-enricher
  uid: d3f86415-c2aa-11e9-984d-02b425e82e0e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coach-enricher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1587159792"
      creationTimestamp: null
      labels:
        app: coach-enricher
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - coach
        - enrich
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:615bafb
        imagePullPolicy: Always
        name: coach
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-08-19T17:57:36Z
    lastUpdateTime: 2019-08-19T17:57:36Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 14
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
