apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "39"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"32"},"creationTimestamp":"2019-08-17T01:43:58Z","generation":51,"labels":{"app":"coach-whitelister"},"name":"coach-whitelister","namespace":"kafka-saas","selfLink":"/apis/apps/v1/namespaces/kafka-saas/deployments/coach-whitelister","uid":"7aed0049-c090-11e9-bc71-0a9e36e5582e"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":5,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"coach-whitelister"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1581975497"},"creationTimestamp":null,"labels":{"app":"coach-whitelister","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=6","coach","whitelist","--app.threat.ratelimit.enabled","--app.threat.ratelimit.debug.no-drop"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:3b36075","imagePullPolicy":"Always","name":"coach","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2019-08-17T01:43:58Z
  generation: 58
  labels:
    app: coach-whitelister
  name: coach-whitelister
  namespace: kafka-saas
  resourceVersion: "232890681"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/coach-whitelister
  uid: 7aed0049-c090-11e9-bc71-0a9e36e5582e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coach-whitelister
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1581975497"
      creationTimestamp: null
      labels:
        app: coach-whitelister
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=6
        - coach
        - whitelist
        - --app.threat.ratelimit.enabled
        - --app.threat.ratelimit.max=1000
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: redis-server
              name: endpoints
        - name: HYPERDARK_CACHE_CLUSTER_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: redis-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: coach
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: 2020-08-27T11:05:39Z
    lastUpdateTime: 2020-08-27T11:05:39Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 58
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
