apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"coach-handler","namespace":"kafka-saas"},"spec":{"replicas":1,"template":{"metadata":{"annotations":null,"labels":{"app":"coach-handler"}},"spec":{"containers":[{"args":["/coach","--log.verbosity=10","handler"],"env":[{"name":"COACH_HANDLER_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/coach:test","imagePullPolicy":"Always","name":"coach","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: 2019-08-16T23:20:59Z
  generation: 13
  labels:
    app: coach-handler
  name: coach-handler
  namespace: kafka-saas
  resourceVersion: "209495780"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/coach-handler
  uid: 8158208b-c07c-11e9-984d-02b425e82e0e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: coach-handler
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1566237038"
      creationTimestamp: null
      labels:
        app: coach-handler
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - coach
        - handle
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:15b448f
        imagePullPolicy: Always
        name: coach
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: 2020-08-07T20:53:38Z
    lastUpdateTime: 2020-08-07T20:53:38Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
