apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "418"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"leadoff-threat-db","namespace":"kafka-saas"},"spec":{"replicas":30,"template":{"metadata":{"annotations":null,"labels":{"app":"leadoff-threat-db","prom":"monitor"}},"spec":{"containers":[{"args":["/leadoff","--log.verbosity=10","threat-db"],"env":[{"name":"LEADOFF_THREAT_DB_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"LEADOFF_THREAT_DB_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"LEADOFF_THREAT_DB_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}},{"name":"LEADOFF_THREAT_DB_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/leadoff:task-283","imagePullPolicy":"Always","name":"leadoff","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: 2019-08-27T14:30:58Z
  generation: 1249
  labels:
    app: leadoff-threat-db
    prom: monitor
  name: leadoff-threat-db
  namespace: kafka-saas
  resourceVersion: "230481098"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/leadoff-threat-db
  uid: 497d31cb-c8d7-11e9-b7e4-02c6bb02f104
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: leadoff-threat-db
      prom: monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1588106964"
      creationTimestamp: null
      labels:
        app: leadoff-threat-db
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - threat
        - db
        - --kafka.input-topic=ThreatDatabaseStream
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: redis-server
              name: endpoints
        - name: HYPERDARK_CACHE_CLUSTER_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: redis-cluster
              name: endpoints
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: postgres-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: leadoff
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 48Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: 2020-09-12T16:59:55Z
    lastUpdateTime: 2020-09-12T16:59:55Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1249
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
