apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "260"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"259"},"creationTimestamp":"2019-08-27T14:30:59Z","generation":322,"labels":{"app":"leadoff-threat-doc","prom":"monitor"},"name":"leadoff-threat-doc","namespace":"kafka-saas","selfLink":"/apis/apps/v1/namespaces/kafka-saas/deployments/leadoff-threat-doc","uid":"49a6c949-c8d7-11e9-b7e4-02c6bb02f104"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":10,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"leadoff-threat-doc","prom":"monitor"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1589811610"},"creationTimestamp":null,"labels":{"app":"leadoff-threat-doc","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=8","leadoff","threat","doc"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"es-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_CREDENTIALS","valueFrom":{"secretKeyRef":{"key":"creds","name":"elastic-user"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:26ea303","imagePullPolicy":"Always","name":"leadoff","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2019-08-27T14:30:59Z
  generation: 341
  labels:
    app: leadoff-threat-doc
    prom: monitor
  name: leadoff-threat-doc
  namespace: kafka-saas
  resourceVersion: "232634826"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/leadoff-threat-doc
  uid: 49a6c949-c8d7-11e9-b7e4-02c6bb02f104
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: leadoff-threat-doc
      prom: monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1589811610"
      creationTimestamp: null
      labels:
        app: leadoff-threat-doc
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=8
        - leadoff
        - threat
        - doc
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_ES_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: es-cluster
              name: endpoints
        - name: HYPERDARK_ES_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: creds
              name: elastic-user
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: leadoff
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: 2020-07-24T02:22:19Z
    lastUpdateTime: 2020-07-24T02:22:19Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 341
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
