apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"name":"leadoff-traffic-filter","namespace":"kafka-saas"},"spec":{"replicas":1,"template":{"metadata":{"annotations":null,"labels":{"app":"leadoff-traffic-filter"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","leadoff","traffic","filter"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:DC-406","imagePullPolicy":"Always","name":"leadoff","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: 2019-08-23T12:01:04Z
  generation: 35
  labels:
    app: leadoff-traffic-filter
  name: leadoff-traffic-filter
  namespace: kafka-saas
  resourceVersion: "201011305"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/leadoff-traffic-filter
  uid: af02c12e-c59d-11e9-984d-02b425e82e0e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: leadoff-traffic-filter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: leadoff-traffic-filter
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - traffic
        - filter
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:DC-406
        imagePullPolicy: Always
        name: leadoff
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-12-13T18:32:19Z
    lastUpdateTime: 2019-12-13T18:32:19Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 35
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
