apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"leadoff-threat-doc-replay","prom":"monitor"},"name":"leadoff-threat-doc-replay","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":30,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"leadoff-threat-doc-replay","prom":"monitor"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1588106754"},"creationTimestamp":null,"labels":{"app":"leadoff-threat-doc-replay","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","--es.credentials=elastic:bdj54q9pnlbbq7j6v5kqbwf6","leadoff","threat","doc","--kafka.input-topic=TempThreatDocStream_2","--kafka.group-name=TempThreatDoc"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"es-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:DC-451","imagePullPolicy":"Always","name":"leadoff","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2020-04-29T14:21:35Z
  generation: 27
  labels:
    app: leadoff-threat-doc-replay
    prom: monitor
  name: leadoff-threat-doc-replay
  namespace: kafka-saas
  resourceVersion: "168595106"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/leadoff-threat-doc-replay
  uid: bb295a64-8a24-11ea-a064-067d46b7253a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: leadoff-threat-doc-replay
      prom: monitor
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1588106754"
      creationTimestamp: null
      labels:
        app: leadoff-threat-doc-replay
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - threat
        - doc
        - --kafka.input-topic=ThreatDocStream_Missing2
        - --kafka.group-name=TempThreatDoc
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_ES_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: es-cluster
              name: endpoints
        - name: HYPERDARK_ES_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: creds
              name: elastic-user
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:26ea303
        imagePullPolicy: Always
        name: leadoff
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2020-05-29T15:00:45Z
    lastUpdateTime: 2020-05-29T15:00:45Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 27
