apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"newsroom-notify-user","prom":"monitor"},"name":"newsroom-notify-user","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"newsroom-notify-user"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"newsroom-notify-user","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","newsroom","notify","user","--smtp.endpoint=email-smtp.us-east-1.amazonaws.com","--smtp.port=587","--smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh","--smtp.from-email=alerts@darkcubed.com"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:125fbaf","imagePullPolicy":"Always","name":"newsroom","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: 2020-02-25T04:44:08Z
  generation: 3
  labels:
    app: newsroom-notify-user
    prom: monitor
  name: newsroom-notify-user
  namespace: kafka-saas
  resourceVersion: "213723286"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/newsroom-notify-user
  uid: 75c964b6-5789-11ea-bc71-0a9e36e5582e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: newsroom-notify-user
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newsroom-notify-user
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - newsroom
        - notify
        - user
        - --smtp.endpoint=email-smtp.us-east-1.amazonaws.com
        - --smtp.port=587
        - --smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh
        - --smtp.from-email=alerts@darkcubed.com
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: newsroom
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2020-07-24T02:22:24Z
    lastUpdateTime: 2020-07-24T02:22:24Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2020-02-25T04:44:08Z
    lastUpdateTime: 2020-08-15T03:42:04Z
    message: ReplicaSet "newsroom-notify-user-6d8fc79968" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
