apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-mute-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-mute-cache
  template:
    metadata:
      labels:
        app: agent-mute-cache
        prom: monitor 
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - agent
        - mute
        - cache
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: kafka-cluster
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: redis-server
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP        
        imagePullPolicy: Never
        name: agent
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
