apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup-score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanup-score
  template:
    metadata:
      annotations:
      labels:
        app: cleanup-score
        prom: monitor 
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - cleanup
        - score
        - --blackbox.endpoint=MOCK
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: kafka-cluster
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: redis-server
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: postgres-cluster
        - name: HYPERDARK_ES_ENDPOINTS
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: es-cluster
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP        
        imagePullPolicy: Never
        name: cleanup
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
