apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadoff-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leadoff-traffic
  template:
    metadata:
      annotations:
      labels:
        app: leadoff-traffic
        prom: monitor 
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - traffic
        - manage
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP        
        imagePullPolicy: Never
        name: leadoff
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
