apiVersion: apps/v1
kind: Deployment
metadata:
  name: leadoff-threat-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leadoff-threat-cache
  template:
    metadata:
      annotations:
      labels:
        app: leadoff-threat-cache
        prom: monitor 
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - threat
        - cache
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: kafka-cluster
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: endpoints
              key: redis-server
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP        
        imagePullPolicy: Never
        name: leadoff
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
