apiVersion: apps/v1
kind: Deployment
metadata:
  name: mascot
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mascot
  template:
    metadata:
      annotations:
      labels:
        app: mascot
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - mascot
        - kafka
        - --app.delay=1s
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: kafka-cluster
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: redis-server
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: postgres-cluster
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        imagePullPolicy: Never
        name: mascot
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
