apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-syslog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-syslog
  template:
    metadata:
      labels:
        app: notifications-syslog
        prom: monitor 
    spec:
      containers:
      - name: agent
        image: hyperdark
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP        
        imagePullPolicy: Never
        args:
        - /hyperdark
        - --log.verbosity=10
        - notifications
        - syslog
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: kafka-cluster
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
