apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-user-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-user-email
  template:
    metadata:
      labels:
        app: notifications-user-email
        prom: monitor
    spec:
      containers:
        - name: agent
          image: hyperdark
          ports:
            - containerPort: 9102
              name: metrics
              protocol: TCP
          imagePullPolicy: Never
          args:
            - /hyperdark
            - --log.verbosity=10
            - notifications
            - email
            - --smtp.endpoint=STDOUT
            - --kafka.input-topic=UserEmailNotificationStream
            - --kafka.group-name=UserEmailNotification
          env:
            - name: HYPERDARK_KAFKA_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: kafka-cluster
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
