apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saasdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saasdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saasdb
  template:
    metadata:
      labels:
        app: saasdb
        prom: monitor 
    spec:
      containers:
      - image: saasdb
        imagePullPolicy: Never
        name: db
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
          protocol: TCP
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data 
          subPath: postgres
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: saasdb
---
apiVersion: v1
kind: Service
metadata:
  name: saasdb
spec:
  ports:
  - name: db
    port: 5432
  selector:
    app: saasdb
