apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cricket-db-vacuum
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - echo "cricket.cmfxlqcsk74c.us-east-2.rds.amazonaws.com:5432:dark3:dark3:yhk9fwTOAKb0h" > .pgpass && chmod 600 .pgpass && vacuumdb -h cricket.cmfxlqcsk74c.us-east-2.rds.amazonaws.com -U dark3 -W --analyze -j 10 dark3
            image: activeshadow/aws-cli
            imagePullPolicy: IfNotPresent
            name: cricket-db-vacuum
            terminationMessagePolicy: FallbackToLogsOnError
          restartPolicy: OnFailure
  schedule: 0 9 * * *
  successfulJobsHistoryLimit: 1
