apiVersion: v1
data:
  credentials: W2RlZmF1bHRdCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IHMxeW5MeEVMSTJKdEpBbk5rdU9TeS9tNFQzVStuVVEvK250Yk4yMlYKYXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBUkVPM05RU0NNS1BFRkRQMgo=
kind: Secret
metadata:
  creationTimestamp: 2020-01-22T19:52:28Z
  name: s3-access-key
  namespace: kafka-saas
  resourceVersion: "108563145"
  selfLink: /api/v1/namespaces/kafka-saas/secrets/s3-access-key
  uid: b7f4e772-3d50-11ea-b7e4-02c6bb02f104
type: Opaque
