apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: failed-syslog-table
spec:
  config:
    cleanup.policy: compact
  partitions: 1
  replicas: 2
  topicName: FailedSyslog-table
