apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: force
spec:
  config:
    cleanup.policy: delete
  partitions: 20
  replicas: 2
  topicName: ForceStream
