apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: report-table
spec:
  config:
    cleanup.policy: compact
  partitions: 20
  replicas: 2
  topicName: Report-table
