apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka
  name: score
spec:
  config:
    cleanup.policy: delete
  partitions: 10
  replicas: 2
  topicName: ScoreStream
