apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2019-08-16T22:31:41Z
  labels:
    managed-by: prometheus-operator
    prometheus-name: prometheus
  name: prometheus-prometheus-rulefiles-0
  namespace: kafka-saas
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: prometheus
    uid: 9e7d6a09-c075-11e9-bc71-0a9e36e5582e
  resourceVersion: "35699696"
  selfLink: /api/v1/namespaces/kafka-saas/configmaps/prometheus-prometheus-rulefiles-0
  uid: 9e80e0c4-c075-11e9-a064-067d46b7253a
