apiVersion: v1
data:
  46258.conf: "source src-46258-tcp {\n  network(\n    port(46258)\n\n    transport(\"tls\")\n\n
    \   tls(\n      peer-verify(\"optional-untrusted\")\n      key-file(\"/var/certs/tls.key\")\n
    \     cert-file(\"/var/certs/tls.crt\")\n    )\n  );\n};\n\ndestination std-out
    {\n  file(\"/dev/stdout\");\n};\n\nlog {\n  source(src-46258-tcp); \n  destination(std-out);\n};\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"46258.conf":"source src-46258-tcp {\n  network(\n    port(46258)\n\n    transport(\"tls\")\n\n    tls(\n      peer-verify(\"optional-untrusted\")\n      key-file(\"/var/certs/tls.key\")\n      cert-file(\"/var/certs/tls.crt\")\n    )\n  );\n};\n\ndestination std-out {\n  file(\"/dev/stdout\");\n};\n\nlog {\n  source(src-46258-tcp); \n  destination(std-out);\n};\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"syslog-ng-configs","namespace":"kafka-saas"}}
  creationTimestamp: 2020-01-09T16:57:51Z
  name: syslog-ng-configs
  namespace: kafka-saas
  resourceVersion: "102527894"
  selfLink: /api/v1/namespaces/kafka-saas/configmaps/syslog-ng-configs
  uid: 2bfc58aa-3301-11ea-b7e4-02c6bb02f104
