apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"meraki","namespace":"kafka-saas"},"spec":{"ports":[{"name":"grpc","port":8080,"protocol":"TCP"}],"selector":{"app":"meraki"}}}
  creationTimestamp: 2019-08-18T22:56:24Z
  name: meraki
  namespace: kafka-saas
  resourceVersion: "36417334"
  selfLink: /api/v1/namespaces/kafka-saas/services/meraki
  uid: 67855a77-c20b-11e9-bc71-0a9e36e5582e
spec:
  clusterIP: 100.69.127.14
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: meraki
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
