apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"scoreboard","namespace":"kafka-saas"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP"}],"selector":{"app":"ui-maintenance"}}}
  creationTimestamp: 2019-08-16T22:01:56Z
  name: scoreboard
  namespace: kafka-saas
  resourceVersion: "36505596"
  selfLink: /api/v1/namespaces/kafka-saas/services/scoreboard
  uid: 76cf391e-c071-11e9-bc71-0a9e36e5582e
spec:
  clusterIP: 100.68.220.89
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: scoreboard
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
