apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-08-16T22:31:41Z
  labels:
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: kafka-saas
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: prometheus
    uid: 9e7d6a09-c075-11e9-bc71-0a9e36e5582e
  resourceVersion: "35699698"
  selfLink: /api/v1/namespaces/kafka-saas/services/prometheus-operated
  uid: 9e848a8a-c075-11e9-a064-067d46b7253a
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
