apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"exported-prometheus":"true","prom":"monitor"},"name":"prometheus-exported","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics-postgres","port":9187,"protocol":"TCP","targetPort":9187}],"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: 2019-12-04T18:36:28Z
  labels:
    exported-prometheus: "true"
    prom: monitor
  name: prometheus-exported
  namespace: kafka-saas
  resourceVersion: "83598660"
  selfLink: /api/v1/namespaces/kafka-saas/services/prometheus-exported
  uid: fbbd0e57-16c4-11ea-b7e4-02c6bb02f104
spec:
  clusterIP: 100.70.78.238
  ports:
  - name: metrics-postgres
    port: 9187
    protocol: TCP
    targetPort: 9187
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
