apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "49"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"catcher-listener"},"name":"catcher-listener","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"catcher-listener"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"date":"1596117081"},"creationTimestamp":null,"labels":{"app":"catcher-listener"}},"spec":{"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["catcher-listener"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"containers":[{"args":["/hyperdark","--log.verbosity=9","catcher","listen","--checkpoint.config-file=/etc/config/checkpoint.yml","--kafka.async-send"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster-external","name":"endpoints"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca","imagePullPolicy":"Always","name":"catcher","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError","volumeMounts":[{"mountPath":"/var/certs","name":"certs"},{"mountPath":"/etc/config","name":"configs"}]}],"dnsPolicy":"ClusterFirst","hostNetwork":true,"nodeSelector":{"kops.k8s.io/instancegroup":"syslog"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"dedicated","value":"udp-syslog"}],"volumes":[{"name":"certs","secret":{"defaultMode":420,"secretName":"syslog-tls"}},{"configMap":{"defaultMode":420,"name":"checkpoint-config"},"name":"configs"}]}}}}
  creationTimestamp: "2019-08-20T04:39:47Z"
  generation: 69
  labels:
    app: catcher-listener
  name: catcher-listener
  namespace: kafka-saas
  resourceVersion: "131842722"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/catcher-listener
  uid: 89fdb5c6-c304-11e9-845f-0a9658482414
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: catcher-listener
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1596117081"
      creationTimestamp: null
      labels:
        app: catcher-listener
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - catcher-listener
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=9
        - catcher
        - listen
        - --checkpoint.config-file=/etc/config/checkpoint.yml
        - --kafka.async-send
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster-external
              name: endpoints
        image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: catcher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/certs
          name: certs
        - mountPath: /etc/config
          name: configs
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kops.k8s.io/instancegroup: syslog
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        value: udp-syslog
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: syslog-tls
      - configMap:
          defaultMode: 420
          name: checkpoint-config
        name: configs
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-08-27T03:17:06Z"
    lastUpdateTime: "2020-08-27T03:17:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 69
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
