apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"cleanup-report","namespace":"kafka-saas"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"cleanup-report"}},"template":{"metadata":{"labels":{"app":"cleanup-report"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","cleanup","report","--blackbox.endpoint=https://prod.deception.a.darkcubed.net","--blackbox.mode=api"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"HYPERDARK_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}},{"name":"HYPERDARK_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:6e73f41","imagePullPolicy":"Always","name":"cleanup","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: "2019-09-17T03:49:32Z"
  generation: 40
  labels:
    app: cleanup-report
  name: cleanup-report
  namespace: kafka-saas
  resourceVersion: "130858316"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/cleanup-report
  uid: 28c98334-d8fe-11e9-9cf6-0248cac6057a
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cleanup-report
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1589913567"
      creationTimestamp: null
      labels:
        app: cleanup-report
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - cleanup
        - report
        - --blackbox.endpoint=https://prod.deception.a.darkcubed.net
        - --blackbox.mode=api
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_CACHE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: redis-server
              name: endpoints
        - name: HYPERDARK_CACHE_CLUSTER_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: redis-cluster
              name: endpoints
        - name: HYPERDARK_DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: postgres-cluster
              name: endpoints
        - name: CLEANUP_REPORT_BLACKBOX_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: bearer-token
              name: scorecard-auth
        image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: cleanup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-15T01:03:33Z"
    lastUpdateTime: "2020-09-15T01:03:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 40
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
