apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"trainer-percentage","namespace":"kafka-saas"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":1,"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["/trainer","--log.verbosity=10","percentage"],"env":[{"name":"TRAINER_PERCENTAGE_CACHE_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"redis-server","name":"endpoints"}}},{"name":"TRAINER_PERCENTAGE_CACHE_CLUSTER_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"redis-cluster","name":"endpoints"}}},{"name":"TRAINER_PERCENTAGE_DB_ENDPOINT","valueFrom":{"secretKeyRef":{"key":"postgres-cluster","name":"endpoints"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/trainer:v1.0.0","imagePullPolicy":"Always","name":"trainer","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"restartPolicy":"Never"}}}},"schedule":"0/5 * * * *","successfulJobsHistoryLimit":1}}
  creationTimestamp: "2019-08-20T15:51:05Z"
  name: trainer-percentage
  namespace: kafka-saas
  resourceVersion: "102463834"
  selfLink: /apis/batch/v1beta1/namespaces/kafka-saas/cronjobs/trainer-percentage
  uid: 51d74520-c362-11e9-9cf6-0248cac6057a
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /trainer
            - --log.verbosity=10
            - percentage
            env:
            - name: TRAINER_PERCENTAGE_CACHE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: redis-server
                  name: endpoints
            - name: TRAINER_PERCENTAGE_CACHE_CLUSTER_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  key: redis-cluster
                  name: endpoints
            - name: TRAINER_PERCENTAGE_DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: postgres-cluster
                  name: endpoints
            image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/trainer:v1.0.0
            imagePullPolicy: Always
            name: trainer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: FallbackToLogsOnError
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0/5 * * * *
  successfulJobsHistoryLimit: 1
  suspend: true
status:
  lastScheduleTime: "2020-06-17T17:20:00Z"
