apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"kafka-minion","namespace":"kafka-saas"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"kafka-minion"}},"template":{"metadata":{"labels":{"app":"kafka-minion"}},"spec":{"containers":[{"env":[{"name":"TELEMETRY_HOST","value":"0.0.0.0"},{"name":"TELEMETRY_PORT","value":"8080"},{"name":"EXPORTER_IGNORE_SYSTEM_TOPICS","value":"true"},{"name":"METRICS_PREFIX","value":"kafka_minion"},{"name":"LOG_LEVEL","value":"info"},{"name":"KAFKA_BROKERS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"KAFKA_SASL_ENABLED","value":"false"},{"name":"KAFKA_CONSUMER_OFFSETS_TOPIC_NAME","value":"__consumer_offsets"},{"name":"KAFKA_TLS_ENABLED","value":"false"}],"image":"quay.io/google-cloud-tools/kafka-minion:v1.0.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthcheck","port":"http"},"initialDelaySeconds":0,"periodSeconds":10,"timeoutSeconds":5},"name":"kafka-minion","ports":[{"containerPort":8080,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":60,"httpGet":{"path":"/readycheck","port":"http"},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":5},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: "2019-09-27T05:03:46Z"
  generation: 5
  name: kafka-minion
  namespace: kafka-saas
  resourceVersion: "122377738"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/kafka-minion
  uid: 2f6a111c-e0e4-11e9-845f-0a9658482414
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-minion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-minion
    spec:
      containers:
      - env:
        - name: TELEMETRY_HOST
          value: 0.0.0.0
        - name: TELEMETRY_PORT
          value: "8080"
        - name: EXPORTER_IGNORE_SYSTEM_TOPICS
          value: "true"
        - name: METRICS_PREFIX
          value: kafka_minion
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: KAFKA_SASL_ENABLED
          value: "false"
        - name: KAFKA_CONSUMER_OFFSETS_TOPIC_NAME
          value: __consumer_offsets
        - name: KAFKA_TLS_ENABLED
          value: "false"
        image: quay.io/google-cloud-tools/kafka-minion:v1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: kafka-minion
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /readycheck
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-08-01T15:28:52Z"
    lastUpdateTime: "2020-08-01T15:28:52Z"
    message: ReplicaSet "kafka-minion-dd8fc8c89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-08-01T16:32:24Z"
    lastUpdateTime: "2020-08-01T16:32:24Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
