apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"leadoff-traffic-doc","namespace":"kafka-saas"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"leadoff-traffic-doc"}},"template":{"metadata":{"labels":{"app":"leadoff-traffic-doc","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","leadoff","traffic","doc"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"es-cluster","name":"endpoints"}}},{"name":"HYPERDARK_ES_CREDENTIALS","valueFrom":{"secretKeyRef":{"key":"creds","name":"elastic"}}},{"name":"HYPERDARK_ES_SENSOR_SALT","valueFrom":{"secretKeyRef":{"key":"sensor-salt","name":"elastic"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:6e73f41","imagePullPolicy":"Always","name":"leadoff","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{"requests":{"cpu":"200m"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}]}}}}
  creationTimestamp: "2019-10-07T12:22:27Z"
  generation: 10
  labels:
    app: leadoff-traffic-doc
    prom: monitor
  name: leadoff-traffic-doc
  namespace: kafka-saas
  resourceVersion: "124672412"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/leadoff-traffic-doc
  uid: 200c226c-e8fd-11e9-9ac2-06e5485013f2
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: leadoff-traffic-doc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        date: "1588107268"
      creationTimestamp: null
      labels:
        app: leadoff-traffic-doc
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - leadoff
        - traffic
        - doc
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        - name: HYPERDARK_ES_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: es-cluster
              name: endpoints
        - name: HYPERDARK_ES_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: creds
              name: elastic
        - name: HYPERDARK_ES_SENSOR_SALT
          valueFrom:
            secretKeyRef:
              key: sensor-salt
              name: elastic
        image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: leadoff
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2019-10-07T12:22:27Z"
    lastUpdateTime: "2020-04-28T20:54:31Z"
    message: ReplicaSet "leadoff-traffic-doc-6ff8589f59" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-08-27T03:18:06Z"
    lastUpdateTime: "2020-08-27T03:18:06Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 10
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
