apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2020-03-06T04:00:51Z","generation":5,"name":"newsroom-notify-user","namespace":"kafka-saas","resourceVersion":"124674392","selfLink":"/apis/extensions/v1beta1/namespaces/kafka-saas/deployments/newsroom-notify-user","uid":"122a0215-5f5f-11ea-845f-0a9658482414"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"newsroom-notify-user"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"newsroom-notify-user"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","newsroom","notify","user","--smtp.endpoint=email-smtp.us-east-1.amazonaws.com","--smtp.port=587","--smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh","--smtp.from-email=support@darkcubed.com"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:0d5a6c7","imagePullPolicy":"Always","name":"newsroom","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2020-03-06T04:00:51Z"
  generation: 6
  labels:
    app: newsroom-notify-user
  name: newsroom-notify-user
  namespace: kafka-saas
  resourceVersion: "127650479"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/newsroom-notify-user
  uid: 122a0215-5f5f-11ea-845f-0a9658482414
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: newsroom-notify-user
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: newsroom-notify-user
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - newsroom
        - notify
        - user
        - --smtp.endpoint=email-smtp.us-east-1.amazonaws.com
        - --smtp.port=587
        - --smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh
        - --smtp.from-email=support@darkcubed.com
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: newsroom
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-27T03:25:51Z"
    lastUpdateTime: "2020-08-27T03:25:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-06T04:00:51Z"
    lastUpdateTime: "2020-09-05T05:41:33Z"
    message: ReplicaSet "newsroom-notify-user-7b4599f7fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
