apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"notifications-email","prom":"monitor"},"name":"notifications-email","namespace":"kafka-saas"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"notifications-email"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"notifications-email","prom":"monitor"}},"spec":{"containers":[{"args":["/hyperdark","--log.verbosity=10","notifications","email","--smtp.endpoint=email-smtp.us-east-1.amazonaws.com","--smtp.port=587","--smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh","--smtp.from-email=alerts@darkcubed.com"],"env":[{"name":"HYPERDARK_KAFKA_ENDPOINTS","valueFrom":{"configMapKeyRef":{"key":"kafka-cluster","name":"endpoints"}}}],"image":"944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:0d5a6c7","imagePullPolicy":"Always","name":"agent","ports":[{"containerPort":9102,"name":"metrics","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"FallbackToLogsOnError"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}}}
  creationTimestamp: "2020-09-05T04:05:12Z"
  generation: 1
  labels:
    app: notifications-email
    prom: monitor
  name: notifications-email
  namespace: kafka-saas
  resourceVersion: "127628465"
  selfLink: /apis/extensions/v1beta1/namespaces/kafka-saas/deployments/notifications-email
  uid: ff07c0fd-ef2c-11ea-863b-0644f009faae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notifications-email
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notifications-email
        prom: monitor
    spec:
      containers:
      - args:
        - /hyperdark
        - --log.verbosity=10
        - notifications
        - email
        - --smtp.endpoint=email-smtp.us-east-1.amazonaws.com
        - --smtp.port=587
        - --smtp.credentials=AKIAJF2K33UAT7QC2QNQ:AmHQd3vAB3ylF6xTNOuo7zhQOD6DFT19sa5OM7uFTvYh
        - --smtp.from-email=alerts@darkcubed.com
        env:
        - name: HYPERDARK_KAFKA_ENDPOINTS
          valueFrom:
            configMapKeyRef:
              key: kafka-cluster
              name: endpoints
        image: 944254975049.dkr.ecr.us-gov-west-1.amazonaws.com/darkcubed-gov/hyperdark:f2d65ca
        imagePullPolicy: Always
        name: agent
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-05T04:05:13Z"
    lastUpdateTime: "2020-09-05T04:05:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-05T04:05:12Z"
    lastUpdateTime: "2020-09-05T04:05:13Z"
    message: ReplicaSet "notifications-email-54b7c7b7cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
