apiVersion: v1
data:
  secret-access-key: cmp2a1dtNWVyRk92S203U0VQQzI4VU9yeVFBSlBDMmYvVkhPVE14Vwo=
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"secret-access-key":"cmp2a1dtNWVyRk92S203U0VQQzI4VU9yeVFBSlBDMmYvVkhPVE14Vwo="},"kind":"Secret","metadata":{"annotations":{},"name":"route53-access-key","namespace":"kafka-saas"},"type":"Opaque"}
  creationTimestamp: "2019-08-19T22:47:55Z"
  name: route53-access-key
  namespace: kafka-saas
  resourceVersion: "6036133"
  selfLink: /api/v1/namespaces/kafka-saas/secrets/route53-access-key
  uid: 622d581d-c2d3-11e9-845f-0a9658482414
type: Opaque
