apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"agent-mute","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"agent-mute"}}}
  creationTimestamp: "2019-08-20T06:42:19Z"
  labels:
    prom: monitor
  name: agent-mute
  namespace: kafka-saas
  resourceVersion: "6126748"
  selfLink: /api/v1/namespaces/kafka-saas/services/agent-mute
  uid: a86272ca-c315-11e9-845f-0a9658482414
spec:
  clusterIP: 100.68.220.122
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: agent-mute
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
