apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"coach-whitelister","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"coach-whitelister"}}}
  creationTimestamp: "2019-08-20T06:33:33Z"
  labels:
    prom: monitor
  name: coach-whitelister
  namespace: kafka-saas
  resourceVersion: "6124867"
  selfLink: /api/v1/namespaces/kafka-saas/services/coach-whitelister
  uid: 6e7b5179-c314-11e9-9ac2-06e5485013f2
spec:
  clusterIP: 100.71.112.112
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: coach-whitelister
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
