apiVersion: v1
kind: Service
metadata:
  labels:
    prom: monitor
  name: catcher-processor-lm
  namespace: kafka-saas
spec:
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: catcher-processor-lm
  sessionAffinity: None
  type: ClusterIP
