apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"cleanup-report","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"cleanup-report"}}}
  creationTimestamp: "2019-08-20T13:20:13Z"
  labels:
    prom: monitor
  name: cleanup-report
  namespace: kafka-saas
  resourceVersion: "6204287"
  selfLink: /api/v1/namespaces/kafka-saas/services/cleanup-report
  uid: 3e7bdb98-c34d-11e9-845f-0a9658482414
spec:
  clusterIP: 100.66.36.140
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: cleanup-report
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
