apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"catcher-listener","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"catcher-listener"}}}
  creationTimestamp: "2019-08-20T04:39:47Z"
  labels:
    prom: monitor
  name: catcher-listener
  namespace: kafka-saas
  resourceVersion: "6103317"
  selfLink: /api/v1/namespaces/kafka-saas/services/catcher-listener
  uid: 8a003465-c304-11e9-845f-0a9658482414
spec:
  clusterIP: 100.67.17.65
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: catcher-listener
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
