apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: b0.kafka-cluster.darkcubed-gov.saas-gov
    external-dns.alpha.kubernetes.io/ttl: "300"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: kube_namespace=kafka-saas,lb-scope=per-pod,zone=us-gov-west-1c
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  creationTimestamp: "2019-08-20T04:31:44Z"
  name: kafka-0-lb
  namespace: kafka-saas
  resourceVersion: "6101746"
  selfLink: /api/v1/namespaces/kafka-saas/services/kafka-0-lb
  uid: 69e981f9-c303-11e9-845f-0a9658482414
spec:
  clusterIP: 100.67.164.64
  externalTrafficPolicy: Local
  healthCheckNodePort: 31546
  ports:
  - nodePort: 31210
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    physicalstatefulcluster.core.confluent.cloud/name: kafka
    physicalstatefulcluster.core.confluent.cloud/version: v1
    statefulset.kubernetes.io/pod-name: kafka-0
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: internal-a69e981f9c30311e9845f0a965848241-1228304732.us-gov-west-1.elb.amazonaws.com
