apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"leadoff-traffic-filter","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"leadoff-traffic-filter"}}}
  creationTimestamp: "2019-10-07T12:18:55Z"
  labels:
    prom: monitor
  name: leadoff-traffic-filter
  namespace: kafka-saas
  resourceVersion: "20339580"
  selfLink: /api/v1/namespaces/kafka-saas/services/leadoff-traffic-filter
  uid: a1e88851-e8fc-11e9-845f-0a9658482414
spec:
  clusterIP: 100.65.210.242
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: leadoff-traffic-filter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
