apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"leadoff-threat","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"leadoff-threat"}}}
  creationTimestamp: "2019-08-20T06:35:48Z"
  labels:
    prom: monitor
  name: leadoff-threat
  namespace: kafka-saas
  resourceVersion: "6125318"
  selfLink: /api/v1/namespaces/kafka-saas/services/leadoff-threat
  uid: bee0696e-c314-11e9-9cf6-0248cac6057a
spec:
  clusterIP: 100.65.96.216
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: leadoff-threat
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
