apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2019-08-20T04:31:42Z"
  name: kafka
  namespace: kafka-saas
  resourceVersion: "6101703"
  selfLink: /api/v1/namespaces/kafka-saas/services/kafka
  uid: 68f3b5da-c303-11e9-845f-0a9658482414
spec:
  clusterIP: None
  ports:
  - name: internal
    port: 9071
    protocol: TCP
    targetPort: 9071
  - name: replication
    port: 9072
    protocol: TCP
    targetPort: 9072
  - name: external
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: jmx
    port: 7203
    protocol: TCP
    targetPort: 7203
  - name: jolokia
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    type: kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
