apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"catcher-processor","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"catcher-processor"}}}
  creationTimestamp: "2019-08-20T06:29:18Z"
  labels:
    prom: monitor
  name: catcher-processor
  namespace: kafka-saas
  resourceVersion: "6123941"
  selfLink: /api/v1/namespaces/kafka-saas/services/catcher-processor
  uid: d6d8c19a-c313-11e9-845f-0a9658482414
spec:
  clusterIP: 100.66.160.99
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: catcher-processor
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
