apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"cleanup-score","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"cleanup-score"}}}
  creationTimestamp: "2019-09-17T03:45:18Z"
  labels:
    prom: monitor
  name: cleanup-score
  namespace: kafka-saas
  resourceVersion: "14097262"
  selfLink: /api/v1/namespaces/kafka-saas/services/cleanup-score
  uid: 90ea5cbf-d8fd-11e9-845f-0a9658482414
spec:
  clusterIP: 100.70.105.230
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: cleanup-score
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
