apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"scoreboard-beta","namespace":"kafka-saas"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP"},{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"scoreboard-beta"}}}
  creationTimestamp: "2019-12-10T20:57:40Z"
  name: scoreboard-beta
  namespace: kafka-saas
  resourceVersion: "40751936"
  selfLink: /api/v1/namespaces/kafka-saas/services/scoreboard-beta
  uid: b3ff4a6c-1b8f-11ea-845f-0a9658482414
spec:
  clusterIP: 100.71.185.216
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: scoreboard-beta
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
