apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"leadoff-traffic","namespace":"kafka-saas"},"spec":{"ports":[{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"leadoff-traffic"}}}
  creationTimestamp: "2019-08-20T06:36:21Z"
  labels:
    prom: monitor
  name: leadoff-traffic
  namespace: kafka-saas
  resourceVersion: "6125439"
  selfLink: /api/v1/namespaces/kafka-saas/services/leadoff-traffic
  uid: d2a09ad0-c314-11e9-845f-0a9658482414
spec:
  clusterIP: 100.65.34.199
  ports:
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: leadoff-traffic
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
