apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"prom":"monitor"},"name":"scoreboard","namespace":"kafka-saas"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP"},{"name":"metrics","port":9102,"protocol":"TCP"}],"selector":{"app":"scoreboard"}}}
  creationTimestamp: "2019-08-20T06:47:27Z"
  labels:
    prom: monitor
  name: scoreboard
  namespace: kafka-saas
  resourceVersion: "6127777"
  selfLink: /api/v1/namespaces/kafka-saas/services/scoreboard
  uid: 5fe1fb90-c316-11e9-9ac2-06e5485013f2
spec:
  clusterIP: 100.71.139.10
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: scoreboard
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
