apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  creationTimestamp: "2019-08-19T22:02:26Z"
  labels:
    namespace: kafka-saas
    type: zookeeper
  name: zookeeper
  namespace: kafka-saas
  resourceVersion: "6027197"
  selfLink: /api/v1/namespaces/kafka-saas/services/zookeeper
  uid: 07a2d468-c2cd-11e9-845f-0a9658482414
spec:
  clusterIP: None
  ports:
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: peer
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: jmx
    port: 7203
    protocol: TCP
    targetPort: 7203
  - name: jolokia
    port: 7777
    protocol: TCP
    targetPort: 7777
  selector:
    type: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
