apiVersion: v1
kind: Secret
metadata:
  name: scorecard-auth
data:
  # Use some known string that we can use in other scripts to generate JWT Tokens for local dev
  #Base 64 encoded: d3oc-scorecard-secret-dev-only
  jwt-secret-key: ZDNvYy1zY29yZWNhcmQtc2VjcmV0LWRldi1vbmx5
