apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: activeshadow/beanstalkd
        imagePullPolicy: IfNotPresent
        name: beanstalk
        ports:
        - containerPort: 11300
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      - args:
        - /darkmon
        - stalker
        image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/darkmon
        imagePullPolicy: IfNotPresent
        name: stalker
        ports:
        - containerPort: 9102
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prom: monitor
  name: queue
spec:
  ports:
  - name: beanstalk
    port: 11300
    protocol: TCP
    targetPort: 11300
  - name: metrics
    port: 9102
    protocol: TCP
    targetPort: 9102
  selector:
    app: queue
