apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: repair-threat-index
spec:
  schedule: 0 6 * * 6
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: repair-threat-index
              image: 078306444420.dkr.ecr.us-east-2.amazonaws.com/darkcubed/hyperdark:PR-154
              args:
                - /hyperdark
                - '--log.verbosity=6'
                - utils
                - fixup
                - elastic
                - repair-threat-index
                - '--dry-run'
              env:
              - name: HYPERDARK_CACHE_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: redis-server
              - name: HYPERDARK_DB_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: postgres-cluster
              - name: HYPERDARK_ES_ENDPOINTS
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: es-cluster
              resources:
                limits:
                  cpu: 500m
                  memory: 300Mi
                requests:
                  cpu: 250m
                  memory: 300Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Never
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
