apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-scores
spec:
  schedule: 0 * * * *
  startingDeadlineSeconds: 10000
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: update-scores
              image: hyperdark
              args:
                - /hyperdark
                - '--log.verbosity=5'
                - utils
                - update-scores
                - '--app.window=1h'
              env:
              - name: HYPERDARK_KAFKA_ENDPOINTS
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: kafka-cluster
              - name: HYPERDARK_CACHE_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: redis-server
              - name: HYPERDARK_DB_ENDPOINT
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: postgres-cluster
              - name: HYPERDARK_ES_ENDPOINTS
                valueFrom:
                  configMapKeyRef:
                    name: endpoints
                    key: es-cluster
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: FallbackToLogsOnError
              imagePullPolicy: Never
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
